### ISSUE TITLE
URL not found for requirements

### ISSUE THREAD

**Issue by Pcyyy** [kamsec/crypto-bot#2]
Hey There!

I am experiencing an issue when trying to install the requirements for the bot to run.
What I am getting currently is:

`Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://google-coral.github.io/py-repo/aiohttp/`

And it seems that the URL is indeed not working.
Was just wondering if the project has been dropped or if the website used has changed, and how to set up the bot properly at this point.
Thanks in advance!

**Comment by kamsec** [comment]
Hey, thanks for posting that issue.

I was trying to make single `requirements.txt` file for both RPi and Windows and it was working correctly back then, but now it turns out that there is some problem with conditions and `--extra-index-url`. I replaced `requirements.txt` with `requirements_rpi.txt` and `requirements_win,txt` and updated description.

Should be fixed now.

**Comment by Pcyyy** [comment]
> Should be fixed now.

Hi! Thanks for quick and effective fix! That part works well now.
Something else that I am experiencing now however, as I have tried to start the bot for the first time, is the following error.

` File "bot.py", line 5, in <module>
    from src.predict import predict_next
  File "/home/pi/crypto-bot/src/predict.py", line 4, in <module>
    import tflite_runtime.interpreter as tflite
ModuleNotFoundError: No module named 'tflite_runtime'`

And the program cannot find tflite_runtime. Did you update anything else with fixing the issue? I have updated the requirements file but kept everything else as it was before.

Thanks in advance!

**Comment by kamsec** [comment]
On what device and OS are you trying to set it up?

Also, can you open python console and type:
```
>>> import platform
>>> platform.machine()
```
and post the output you get?

**Comment by Pcyyy** [comment]
Sorry I should've specified this as well:
I am currently trying to set it up on a Raspberry Pi 400 running Linux 10 (Buster)
For python, output is "armv7l"

Let me know if this helps!

**Comment by kamsec** [comment]
I added to the project tflite for armv7l, but I don't have Raspberry Pi with armv7l processor to check if it works. It is also different version of tflite - it might or might not work - you can check and let me know.

I also changed the requirements file so it will attempt to install it with `pip install -r requirements_rpi.txt` and detect if you are on armv7l platform. Just follow the instruction steps as before.

**Comment by Pcyyy** [comment]
Hi! Thanks for all the updates, I have done as suggested and the problem now seems to be in ctypes within tflite.
This is the error:
`Traceback (most recent call last):
  File "bot.py", line 5, in <module>
    from src.predict import predict_next
  File "/home/pi/crypto-bot/src/predict.py", line 4, in <module>
    import tflite_runtime.interpreter as tflite
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 21, in <module>
    import ctypes
  File "/home/pi/.local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
`
Let me know if this helps. And btw all this work for adapting it is super appreciated!

**Comment by kamsec** [comment]
Well, I don't have a way to test this, but ppl getting similar error seems to fix it by installing libffi-dev and re-installing python3.7.
You can try to follow some instructions from answers in these links:

[https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul](https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul)

[https://stackoverflow.com/questions/51187725/python-3-7-0-installation-on-raspbian-fails-with-modulenotfounderror-no-module?noredirect=1&lq=1](https://stackoverflow.com/questions/51187725/python-3-7-0-installation-on-raspbian-fails-with-modulenotfounderror-no-module?noredirect=1&lq=1)

Let me know if you managed to make it work.
